CREATE SEQUENCE ACETP.BDOMO_GRM_TRD_CB_MSGS_DB_ID_Test
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE ACETP.SEQ_CL_BUSINESS_FILE_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE ACETP.CB_MSG (
    CB_MSG_DB_ID NUMBER(15) NOT NULL,
    CB_BIZ_EVT_DB_ID NUMBER(15),
    CB_FILE_DB_ID NUMBER(15),
    ACCOUNT_ID VARCHAR2(40),
    DEVICE VARCHAR2(8),
    MSG_TYPE VARCHAR2(20),
    MSG_FUNCTION VARCHAR2(6),
    MSG_GROUP VARCHAR2(6),
    MSG_FAMILY VARCHAR2(32),
    MUR_IMR VARCHAR2(40),
    ISIN VARCHAR2(12),
    SENDER_ADDR VARCHAR2(30),
    RECEIVER_ADDR VARCHAR2(100),
    EVENT_TYPE VARCHAR2(9),
    EVENT_GROUP VARCHAR2(6),
    TO_BE_SENT NUMBER(1),
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATING_DATE DATE,
    VERSION_NUM NUMBER NOT NULL,
    ORIGINAL_MUR_IMR VARCHAR2(40),
    MERGED_NBR NUMBER,
    HSKP_STATUS CHAR(2) DEFAULT 'NW' NOT NULL,
    BRANCH_DB_ID NUMBER(4) NOT NULL,
    ENTITY_DB_ID NUMBER(4),
    SENDER_TIMESTAMP VARCHAR2(20),
    GRP_USER_DB_ID NUMBER(15),
    LINE_START NUMBER(15) DEFAULT -1 NOT NULL,
    LINE_END NUMBER(15) DEFAULT -1 NOT NULL,
    ERROR_OBJ CLOB,
    MODIFIED_MESSAGE CLOB,
    PHYSICAL_MESSAGE CLOB,
    BIZ_TRACKING_ID VARCHAR2(80),
    BP_ROLE_ID VARCHAR2(30),
    BP_ROLE_TYPE VARCHAR2(20),
    DIRECTION VARCHAR2(6) NOT NULL,
    SCHEDULE_ID VARCHAR2(16),
    SENDER_REF VARCHAR2(35),
    TECHNICAL_TYPE VARCHAR2(2) NOT NULL,
    STATUS_TYPE VARCHAR2(6) NOT NULL,
    RECEIVER_REF VARCHAR2(30),
    TRACKING_ID VARCHAR2(80),
    PERSISTENT_TRACKING_ID VARCHAR2(80),
    REPROCESS_TRACKING_ID VARCHAR2(80),
    FUNCTIONAL_KEY VARCHAR2(1000),
    CY_INX_ID VARCHAR2(35),
    CURRENT_REPROCESS_NBR NUMBER(11) DEFAULT -1 NOT NULL,
    BIZ_MSG_IDR VARCHAR2(40),
    PSET VARCHAR2(35),
    PSAFE VARCHAR2(35),
    BD_SECTOR_DB_ID NUMBER(15),
    SP_DB_ID NUMBER(15),
    SHINE VARCHAR2(8),
    EZF_PROC_STATUS VARCHAR2(20) NOT NULL,
    EZF_CLAIM_TOKEN VARCHAR2(64),
    EZF_CLAIMED_BY VARCHAR2(64),
    EZF_CLAIMED_AT DATE,
    EZF_TRY_COUNT NUMBER(10) NOT NULL,
    EZF_LAST_ERROR VARCHAR2(2000),
    EZF_LOGICAL_FILE_NAME VARCHAR2(200),
    CONSTRAINT PK_CB_MSG PRIMARY KEY (CB_MSG_DB_ID),
    CONSTRAINT CK_CB_MSG_EZF_STATUS CHECK (EZF_PROC_STATUS IN ('NEW','IN_PROGRESS','DONE','ERROR'))
);

CREATE TABLE ACETP.CL_BUSINESS_MTM_IN (
    FILE_ID NUMBER(15) NOT NULL,
    LINE_START NUMBER(15),
    LINE_END NUMBER(15),
    MSG_ID NUMBER(16) NOT NULL,
    FCT_MSG VARCHAR2(3),
    STATUS_PREVTRX VARCHAR2(2),
    BANK_CODE VARCHAR2(5),
    ENTITY_CODE VARCHAR2(5),
    APP_CODE VARCHAR2(8),
    CLIENT_ID VARCHAR2(11),
    CASH_ACCOUNT VARCHAR2(11),
    REV_IRREVOCABLE VARCHAR2(1),
    DIRECT_INVERSE VARCHAR2(1),
    CURRENCY_CODE VARCHAR2(3),
    CASH_AMOUNT VARCHAR2(15),
    CURRCODE_FORYWR VARCHAR2(3),
    YWRCASH_AMOUNT VARCHAR2(15),
    REF VARCHAR2(16),
    VALUE_DATE VARCHAR2(8),
    ACCOUNTING_DATE VARCHAR2(8),
    HOUR VARCHAR2(6),
    BOECTDTCD VARCHAR2(1),
    PAYMENT_CHANNEL_GEODE VARCHAR2(3),
    CODEFORMAT_SWIFTCOUNTERPARTY VARCHAR2(1),
    IDENTIFIER_COUNTERPARTY VARCHAR2(35),
    OPERATION_NUM VARCHAR2(16),
    MISCBRANCH_CODE VARCHAR2(4),
    MISCSENDER_RECEIVER VARCHAR2(19),
    ANSWER_TYPE VARCHAR2(2),
    RETURN_CODE VARCHAR2(15),
    FUNCTIONAL_KEY VARCHAR2(1000),
    MSG_TYPE VARCHAR2(10),
    MSG_FAMILY VARCHAR2(20),
    ACCOUNT_ID VARCHAR2(8),
    MSG_REFERENCE VARCHAR2(20),
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    RCA_DB_ID NUMBER(15) DEFAULT 0 NOT NULL,
    REPLY_TO_Q VARCHAR2(50),
    REPLY_TO_QMGR VARCHAR2(50),
    CODED_CH_SET_ID VARCHAR2(50),
    ISIN_CODE VARCHAR2(12),
    CB_MSG_DB_ID NUMBER(15),
    CASH_SYSTEM_ORIGIN VARCHAR2(4),
    MANAGEMENT_SECTOR VARCHAR2(5),
    CASH_MESSAGE VARCHAR2(8),
    PAYMENT_CHANNEL VARCHAR2(20),
    CREDITED_ACCOUNT VARCHAR2(11),
    INTERNAL_REMITTER VARCHAR2(7),
    CONSTRAINT PK_CL_BUSINESS_MTM_IN PRIMARY KEY (FILE_ID, MSG_ID)
);

CREATE INDEX ACETP.INN_CL_BUSINESS_MTM_1
    ON ACETP.CL_BUSINESS_MTM_IN (FILE_ID, MSG_ID, CB_MSG_DB_ID);

CREATE INDEX ACETP.I_CB_MSG_EZF_1
    ON ACETP.CB_MSG (EZF_PROC_STATUS, BRANCH_DB_ID, CREATION_DATE, CB_MSG_DB_ID);

CREATE INDEX ACETP.I_CB_MSG_EZF_2
    ON ACETP.CB_MSG (EZF_PROC_STATUS, EZF_CLAIMED_AT);

CREATE INDEX ACETP.I_CB_MSG_EZF_3
    ON ACETP.CB_MSG (EZF_CLAIM_TOKEN);

CREATE INDEX ACETP.I_CB_MSG_EZF_FILEMODE
    ON ACETP.CB_MSG (EZF_PROC_STATUS, BRANCH_DB_ID, EZF_LOGICAL_FILE_NAME, CB_MSG_DB_ID);
